### ISSUE TITLE
 gcr http 404

### ISSUE THREAD

**Issue by suther** [evanlucas/gcr#14]
I have no experiences with GitLab CI. So I choose to use node.js (https://about.gitlab.com/gitlab-ci/#gitlab-runner) and installed it on my local machine.

I've run gcr after the Installation finished successfully. Than I enter the GitLabCI-URL and my GitLab CI Registration Token.

After this I got a dozen times this message:

>  gcr info [client] checking for builds... 
> gcr http 404 https://ci.gitlab.com/api/v1/builds/register.json
>  gcr info [client] checking for builds... 
>  gcr http 404 https://ci.gitlab.com/api/v1/builds/register.json 

If I enter the above URL in my Browser, the Console give this message:

> Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

**Comment by evanlucas** [comment]
The 404 you are getting is normal. Whenever the client checks for builds, if no builds are available, the request returns a 404.  That is what tells the runner to actually start a new build.
