### ISSUE TITLE
gcr with Windows and ssh-keygen

### ISSUE THREAD

**Issue by Skywalker13** [evanlucas/gcr#5]
in the lib/utils.js script, you look for ~/, but it is not possible with Windows.

    var cmd = 'ssh-keygen -t rsa -f ~/.ssh/gcr -N ""'

Like for the bug #4, you should use USERPROFILE, for example:

    function getUserHome()
    {
      return process.env[process.platform === 'win32' ? 'USERPROFILE' : 'HOME'];
    }

**Comment by radum** [comment]
Quick fix before this gets fixed is to run it manually in git-bash

```bash
ssh-keygen -t rsa -f ~/.ssh/gcr -N ""
```

and that is it.

**Comment by evanlucas** [comment]
Yall mind testing the latest master branch and see if that works? I just tried it with git bash and it worked for me on windows.

**Comment by evanlucas** [comment]
Closed as of 78d5e577e5a4725900cad7e5be2e35c0873439fb. If anyone is still having trouble on Windows, please don't hesitate to open an issue or let me know otherwise. Thanks!

**Comment by radum** [comment]
Just tested on Win 7 x64 looks ok for me. Thanks @evanlucas

**Comment by evanlucas** [comment]
Fantastic!
