### ISSUE TITLE
The config for strictSSL is not handled correctly, it is always true

### ISSUE THREAD

**Issue by Skywalker13** [evanlucas/gcr#6]
You have:

    strictSSL: gcr.config.get('strictSSL') || true

But it will be always true.. because `false || true` returns always true
It seems that strictSSL is always stored in the config file, then it should be just

    strictSSL: gcr.config.get('strictSSL')

Or if this config is optional (not available in the config file), then you should test if it's undefined.. 

Regards

**Comment by evanlucas** [comment]
ah good catch. PR welcome
