### ISSUE TITLE
Will gcr work with gitlabci servers that require authentication?

### ISSUE THREAD

**Issue by geekytime** [evanlucas/gcr#9]
I get a bunch of 403 errors when it tries to get the builds from the server.

I dug around in the issues and the source code, and I don't seen any options for providing credentials. I also tried including my credentials in the url, but I don't think it's configured with basic auth, so I pretty much assumed that wouldn't work.

Are there any hidden options for this that I'm missing?

**Comment by evanlucas** [comment]
you should be able to set your creds in the apiUrl config option
